resources:
  - name: test
    type: GitRepo
    configuration:
      gitProvider: deepak_git
      path: creepy-pirate/testim-check
      branches:
        include: "{{ gitBranch }}"

variables:
  JP_WORKSPACE: "/workspace"  # Default workspace in JFrog Pipelines
  TESTIM_TOKEN: "7Gohf81BZYRrIMLoGBhnNF4wuzCS6is194r0R6Y8NEBUPBBPx5"
  TESTIM_PROJECT: "QCmTIpKSP0XtVRAGVTzU"
  TESTIM_GRID: "Testim-Grid"
  TEST_LABEL: "Login"

pipelines:
  - name: TestimPipeline
    steps:
      - name: SetupEnvironment
        type: Bash
        execution:
          onExecute:
            - echo "Setting up environment"
            - mkdir -p "${JP_WORKSPACE}/.npm-packages"
            - export PATH="$PATH:${JP_WORKSPACE}/.npm-packages/bin"
            - export NODE_PATH="$NODE_PATH:${JP_WORKSPACE}/.npm-packages/lib/node_modules"
            - npm config set prefix ${JP_WORKSPACE}/.npm-packages

      - name: InstallTestimCLI
        type: Bash
        execution:
          onExecute:
            - echo "Installing Testim CLI"
            - npm install -g @testim/testim-cli

      - name: RunTestimTests
        type: Bash
        execution:
          onExecute:
            - echo "Running Testim Tests"
            - testim \
                --label "$TEST_LABEL" \
                --token "$TESTIM_TOKEN" \
                --project "$TESTIM_PROJECT" \
                --grid "$TESTIM_GRID" \
                --report-file test-results/testim-tests-$BUILD_NUMBER-report.xml

      - name: PrintCompletionMessage
        type: Bash
        execution:
          onExecute:
            - echo "Testim finished"
