resources:
  - name: test
    type: GitRepo
    configuration:
      gitProvider: deepak_git
      path: creepy-pirate/testim-check
      branches:
        include: "{{ gitBranch }}"

pipelines:
  - name: TestimPipeline
    configuration:
        environmentVariables:
          readOnly:
            JP_WORKSPACE: "/workspace"
            TESTIM_TOKEN: "7Gohf81BZYRrIMLoGBhnNF4wuzCS6is194r0R6Y8NEBUPBBPx5"
            TESTIM_PROJECT: "QCmTIpKSP0XtVRAGVTzU"
            TESTIM_GRID: "Testim-Grid"
    steps:
      - name: RunTestimTests
        type: Bash
        execution:
          onExecute:
            - echo "Running Testim Tests"
            - echo $JP_WORKSPACE
            - mkdir -p "${JP_WORKSPACE}/.npm-packages"
            - prefix="${JP_WORKSPACE}/.npm-packages"
            - NPM_PACKAGES="${JP_WORKSPACE}/.npm-packages"
            - export PATH="$PATH:$NPM_PACKAGES/bin"
            - export NODE_PATH="$NODE_PATH:$NPM_PACKAGES/lib/node_modules"
            - npm config set prefix "${JP_WORKSPACE}/.npm-packages"
            - npm install -g @testim/testim-cli
            - testim --token "${TESTIM_TOKEN}" --project "${TESTIM_PROJECT}" --grid "${TESTIM_GRID}" --report-file "testim-tests-report.xml"
            - echo "Testim finished"
