resources:
  - name: test
    type: GitRepo
    configuration:
      gitProvider: deepak_git
      path: creepy-pirate/testim-check
      branches:
        include: "{{ gitBranch }}"

pipelines:
  - name: TestimPipeline
    configuration:
        environmentVariables:
          readOnly:
            "BROWSER_NAME":
              default: 'chrome-99-mac'
              description: Choose browser for running tests
              values:
                - 'chrome-99-mac'
                - 'chrome-99-mac-prod'
                - 'ie-11-win'
                - 'edge-18-win'
                - 'safari-13-mac'
            "TESTIM_PROJECT_NAME":
              default: 'website'
              description: Select the project to run tests from
              values:
                - 'website'
            "TESTIM_LABEL":
              default: 'sanity'
              description: Run all tests comprising one of the mentioned labels
              allowCustom: true
              value:
                - 'sanity'
            "TESTIM_BASE_URL":
              default: 'https://jfrog.info'
              description: Starting URL after browser opens
              allowCustom: true
              value:
                - 'https://jfrog.info'
            "TESTIM_PARALLEL":
              default: "4"
              description: How many tests should run in parallel
              allowCustom: true
              value:
                - "4"
            "TESTIM_GRID_HOST":
              default: 'hub-cloud.browserstack.com/wd/hub'
              description: Where to run the tests
              allowCustom: true
              value:
                - 'hub-cloud.browserstack.com/wd/hub'
            "TESTIM_GRID_PORT":
              default: "4444"
              description: Where to run the tests
              allowCustom: true
              value:
                - "4444"
            "TESTIM_BRANCH":
              default: 'master'
              description: Where to run the tests
              allowCustom: true
              value:
                - 'master'
            "TESTIM_SELENIUM_MODE":
              default: 'false'
              description: When you run IE11, Edge, or Safari
              allowCustom: false
              values:
                - 'true'
                - 'false'
            JP_WORKSPACE: "/workspace"
            TESTIM_TOKEN: "7Gohf81BZYRrIMLoGBhnNF4wuzCS6is194r0R6Y8NEBUPBBPx5"
            TESTIM_PROJECT: "QCmTIpKSP0XtVRAGVTzU"
            TESTIM_GRID: "Testim-Grid"
            TESTIM_DOCKER: "testim/docker-cli"
          "EXEC_CMD": ''
        integrations:
            - name: slackIntegration
          
    steps:
      - name: RunTestimTests
        type: Bash
        execution:
          onExecute:
            - EXEC_CMD='docker run --rm -v ${WORKSPACE}:/opt/testim-runner ${TESTIM_DOCKER}'
            - echo "Running Testim Tests"
            - echo "Pulling latest version"
            - docker pull ${TESTIM_DOCKER}
            - echo "Run testim-cli"
            - >-
              if [ "${TESTIM_PROJECT_NAME}" = "website" ]; then
                EXEC_CMD="${EXEC_CMD} --token ${TESTIM_TOKEN} --project ${TESTIM_PROJECT} --grid ${TESTIM_GRID} -r report.xml"
              fi
            - docker run --rm -v ${WORKSPACE}:/opt/testim-runner ${TESTIM_DOCKER} --token ${TESTIM_TOKEN} --project ${TESTIM_PROJECT} --grid ${TESTIM_GRID} -r report.xml
            - sh "${EXEC_CMD}"
            - echo "Testim finished"
          onSuccess:
            - send_notification slackIntegration --text "Success testim-test-pipeline"
          onFailure:
            - send_notification slackIntegration --text "Failure for testim-test-pipeline"
