resources:
  - name: test
    type: GitRepo
    configuration:
      gitProvider: deepak_git
      path: creepy-pirate/testim-check
      branches:
        include: "{{ gitBranch }}"

variables:
  JP_WORKSPACE: "/workspace"  # Default workspace in JFrog Pipelines
  TESTIM_TOKEN: "7Gohf81BZYRrIMLoGBhnNF4wuzCS6is194r0R6Y8NEBUPBBPx5"
  TESTIM_PROJECT: "QCmTIpKSP0XtVRAGVTzU"
  TESTIM_GRID: "Testim-Grid"
  TEST_LABEL: "Login"

pipelines:
  - name: TestimPipeline
    steps:
      - name: RunTestimTests
        type: Bash
        execution:
          onExecute:
            - echo "Running Testim Tests"
            - npm i -g @testim/testim-cli && testim \
                --token "$TESTIM_TOKEN" \
                --project "$TESTIM_PROJECT" \
                --grid "$TESTIM_GRID"
            - echo "Testim finished"
