resources:
  - name: test
    type: GitRepo
    configuration:
      gitProvider: deepak_git
      path: creepy-pirate/testim-check
      branches:
        include: "{{ gitBranch }}"

variables:
  JP_WORKSPACE: "/workspace"  # Default workspace in JFrog Pipelines
  TESTIM_TOKEN: "7Gohf81BZYRrIMLoGBhnNF4wuzCS6is194r0R6Y8NEBUPBBPx5"
  TESTIM_PROJECT: "QCmTIpKSP0XtVRAGVTzU"
  TESTIM_GRID: "Testim-Grid"
  TEST_LABEL: "Login"

pipelines:
  - name: Testim Pipeline
    steps:
      - name: Setup Environment
        image: node:latest
        commands:
          - mkdir -p "${JP_WORKSPACE}/.npm-packages"
          - export PATH="$PATH:${JP_WORKSPACE}/.npm-packages/bin"
          - export NODE_PATH="$NODE_PATH:${JP_WORKSPACE}/.npm-packages/lib/node_modules"
          - npm config set prefix ${JP_WORKSPACE}/.npm-packages

      - name: Install Testim CLI
        image: node:latest
        commands:
          - npm install -g @testim/testim-cli

      - name: Run Testim Tests
        image: node:latest
        commands:
          - testim \
              --label "$TEST_LABEL" \
              --token "$TESTIM_TOKEN" \
              --project "$TESTIM_PROJECT" \
              --grid "$TESTIM_GRID" \
              --report-file test-results/testim-tests-$BUILD_NUMBER-report.xml
        artifacts:
          paths:
            - test-results/*.xml

      - name: Print Completion Message
        image: node:latest
        commands:
          - echo "Testim finished"
